// Code generated by hertz generator.

package neoNode

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _neo_nodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _estoneoMw() []app.HandlerFunc {
	// your code...
	return nil
}
