// Code generated by hertz generator.

package neoNode

import (
	base "GraduateThesis/biz/model/base"
	line "GraduateThesis/biz/model/line"
	"GraduateThesis/biz/service"
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// EsToNeo .
// @router /api/neo_node/es_to_neo [GET]
func EsToNeo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req line.LineReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	err = service.NeoNode.EsToNeo(ctx, &req)
	resp := new(base.SampleResp)
	if err != nil {
		resp.Code = 1
		resp.Data = false
		resp.Message = err.Error()
	} else {
		resp.Data = true
		resp.Code = 0
		resp.Message = ""
	}
	c.JSON(consts.StatusOK, resp)
}
