// Code generated by hertz generator.

package base

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
)

// Healthz .
// @router /healthz [GET]
func Healthz(ctx context.Context, c *app.RequestContext) {
	c.JSON(200, true)
}
