// Code generated by hertz generator.

package line

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _lineMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bulkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changedependenceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _topologyanalyseMw() []app.HandlerFunc {
	// your code...
	return nil
}
