// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	base "GraduateThesis/biz/router/base"
	line "GraduateThesis/biz/router/line"
	node "GraduateThesis/biz/router/node"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	line.Register(r)

	node.Register(r)

	base.Register(r)

}
